### ISSUE TITLE
Petition for a name & logo change

### ISSUE THREAD

**Issue by nvb-uy** [httpedor/AttributeSetter#1]
Hello! I'm the developer of Custom Item Attributes. I saw your description and i'm glad that my mod inspired you to make yours, however the resemblance to CIA is too much which confuses people, and also limits me because I already have an indev project with this exact same name.

I'd appreciate it if you could change it to something else :)

**Comment by httpedor** [comment]
Renamed the project to AttributeSetter.

**Comment by nvb-uy** [comment]
Thank you!
